/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gustavo
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    protected Turma turma;
    /**
     * Creates new form TelaLista08
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfDisciplina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jrbGraduacao = new javax.swing.JRadioButton();
        jrbMestrado = new javax.swing.JRadioButton();
        jrbDoutorado = new javax.swing.JRadioButton();
        jrbMatutino = new javax.swing.JRadioButton();
        jrbVespertino = new javax.swing.JRadioButton();
        jrbNoturno = new javax.swing.JRadioButton();
        buttonIncluir = new javax.swing.JButton();
        buttonListar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        jCheckBox4.setText("jCheckBox4");

        jCheckBox5.setText("jCheckBox5");

        jLabel9.setText("jLabel9");

        jRadioButton1.setText("jRadioButton1");

        jRadioButton5.setText("jRadioButton5");

        jRadioButton9.setText("jRadioButton9");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Turma:");

        jLabel3.setText("Disciplina:");

        jLabel4.setText("Turno:");

        jtfDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDisciplinaActionPerformed(evt);
            }
        });

        jLabel5.setText("Professor:");

        jLabel6.setText("Nome:");

        jLabel7.setText("E-mail:");

        jLabel8.setText("Titulação:");

        jrbGraduacao.setText("Graduação");
        jrbGraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGraduacaoActionPerformed(evt);
            }
        });

        jrbMestrado.setText("Mestrado");
        jrbMestrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMestradoActionPerformed(evt);
            }
        });

        jrbDoutorado.setText("Doutorado");

        jrbMatutino.setText("Matutino");
        jrbMatutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatutinoActionPerformed(evt);
            }
        });

        jrbVespertino.setText("Vespertino");
        jrbVespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVespertinoActionPerformed(evt);
            }
        });

        jrbNoturno.setText("Noturno");
        jrbNoturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNoturnoActionPerformed(evt);
            }
        });

        buttonIncluir.setText("Incluir Aluno");
        buttonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncluirActionPerformed(evt);
            }
        });

        buttonListar.setText("Listar dados da turma");
        buttonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfDisciplina, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbGraduacao)
                                .addGap(18, 18, 18)
                                .addComponent(jrbMestrado)
                                .addGap(18, 18, 18)
                                .addComponent(jrbDoutorado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbMatutino)
                                .addGap(18, 18, 18)
                                .addComponent(jrbVespertino)
                                .addGap(18, 18, 18)
                                .addComponent(jrbNoturno))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(buttonListar)))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jrbMatutino)
                    .addComponent(jrbVespertino)
                    .addComponent(jrbNoturno))
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbGraduacao)
                    .addComponent(jrbMestrado)
                    .addComponent(jrbDoutorado)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIncluir)
                    .addComponent(buttonListar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDisciplinaActionPerformed

    private void jrbMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatutinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMatutinoActionPerformed

    private void jrbGraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGraduacaoActionPerformed
    
    private Turno getTurno() {
        Turno turno = null;
        if (jrbMatutino.isSelected()) {
            turno = Turno.MATUTINO;
        } else if (jrbVespertino.isSelected()) {
            turno = Turno.VESPERTINO;
        } else if (jrbNoturno.isSelected()) {
            turno = Turno.NOTURNO;
        }
        return turno;
    }
    
    private Titulacao getTitulacao() {
        if (jrbGraduacao.isSelected()) {
            return Titulacao.GRADUACAO;
        }
        if (jrbMestrado.isSelected()) {
            return Titulacao.MESTRADO;
        }
        
        return Titulacao.DOUTORADO;
    }
    private void buttonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncluirActionPerformed
        if (turma == null) {
            turma = new Turma(jtfDisciplina.getText(), getTurno(), new Professor(jtfNome.getText(), jtfEmail.getText(), getTitulacao()));
        }
        
        TelaAluno telaAluno = new TelaAluno(this);
        telaAluno.setVisible(true);
    }//GEN-LAST:event_buttonIncluirActionPerformed

    private void buttonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarActionPerformed
        Relatorio telaRelatorio = new Relatorio();
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_buttonListarActionPerformed

    private void jrbVespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVespertinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbVespertinoActionPerformed

    private void jrbMestradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMestradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMestradoActionPerformed

    private void jrbNoturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNoturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNoturnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIncluir;
    private javax.swing.JButton buttonListar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrbDoutorado;
    private javax.swing.JRadioButton jrbGraduacao;
    private javax.swing.JRadioButton jrbMatutino;
    private javax.swing.JRadioButton jrbMestrado;
    private javax.swing.JRadioButton jrbNoturno;
    private javax.swing.JRadioButton jrbVespertino;
    private javax.swing.JTextField jtfDisciplina;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
