/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author adriel, gustavo e guilherme
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private final FileNameExtensionFilter filtroPoo;
    
    private final Sobre s;
    private final Controle c;

    private final SimpleAttributeSet letrasGeral;

    /**
     * Creates new form Tela
     * @param choice
     * @throws javax.swing.text.BadLocationException
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     */
    public TelaPrincipal(int choice) throws BadLocationException, IOException, ClassNotFoundException {
        initComponents();
        
        letrasGeral = new SimpleAttributeSet();
        
        s = new Sobre();
        c = new Controle(this, letrasGeral, tpEscritaReleased, fcAbrirArquivo, fcSalvarComo);
        
        c.trataCorTexto(Color.black);
        c.trataCorMarcador(Color.white);
        
        filtroPoo = new FileNameExtensionFilter("Arquivos POO (*.poo)", "poo");
        
        StyleConstants.setFontSize(letrasGeral, 15);
        c.inicializacaoTexto();
        
        switch (choice) {
            case 1 -> c.abrirArquivo(0);
            case 2 -> c.novoArquivo();
            default -> JOptionPane.showMessageDialog(null, "Erro ao Inicializar o Programa");
        }
    }

    private void showPopUp(MouseEvent e) {
        popupMenu.show(this, e.getX(), e.getY());
    }

    public void atualizaCor() {
        btCorDoTexto.setBackground(c.corTexto);
        btCorMarcaTexto.setBackground(c.corMarcador);
    }
    
    public void mudaNomeDoc(){
        String nome = c.getDocumento().replace(".poo", "");
        lbNomeDoc.setText("Arquivo: " + nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        popTipoTexto = new javax.swing.JMenu();
        popNegrito = new javax.swing.JMenuItem();
        popItalico = new javax.swing.JMenuItem();
        popSublinhado = new javax.swing.JMenuItem();
        popNormal = new javax.swing.JMenuItem();
        popCores = new javax.swing.JMenu();
        popCorTexto = new javax.swing.JMenu();
        pctVermelho = new javax.swing.JMenuItem();
        pctLaranja = new javax.swing.JMenuItem();
        pctAmarelo = new javax.swing.JMenuItem();
        pctVerde = new javax.swing.JMenuItem();
        pctAzul = new javax.swing.JMenuItem();
        pctRoxo = new javax.swing.JMenuItem();
        pctBranco = new javax.swing.JMenuItem();
        popCorMarcador = new javax.swing.JMenu();
        pcmVermelho = new javax.swing.JMenuItem();
        pcmLaranja = new javax.swing.JMenuItem();
        pcmAmarelo = new javax.swing.JMenuItem();
        pcmVerde = new javax.swing.JMenuItem();
        pcmAzul = new javax.swing.JMenuItem();
        pcmRoxo = new javax.swing.JMenuItem();
        pcmPreto = new javax.swing.JMenuItem();
        popFonte = new javax.swing.JMenuItem();
        fcAbrirArquivo = new javax.swing.JFileChooser();
        fcSalvarComo = new javax.swing.JFileChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpEscritaReleased = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        btCorDoTexto = new javax.swing.JButton();
        lbCorDoTexto = new javax.swing.JLabel();
        btCorMarcaTexto = new javax.swing.JButton();
        lbMarcaTexto = new javax.swing.JLabel();
        cbItalico = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        cbNegrito = new javax.swing.JCheckBox();
        cbUnderLine = new javax.swing.JCheckBox();
        lbNomeDoc = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        maAbrir = new javax.swing.JMenuItem();
        maNovo = new javax.swing.JMenuItem();
        maSalvar = new javax.swing.JMenuItem();
        maSalvarComo = new javax.swing.JMenuItem();
        mnTexto = new javax.swing.JMenu();
        mtTipoTexto = new javax.swing.JMenu();
        mtItalico = new javax.swing.JMenuItem();
        mtNegrito = new javax.swing.JMenuItem();
        mtSublinhado = new javax.swing.JMenuItem();
        btFonte = new javax.swing.JMenuItem();
        mtNormal = new javax.swing.JMenuItem();
        mnCores = new javax.swing.JMenu();
        mcCorDoTexto = new javax.swing.JMenu();
        mctVermelho = new javax.swing.JMenuItem();
        mctLaranja = new javax.swing.JMenuItem();
        mctAmarelo = new javax.swing.JMenuItem();
        mctVerde = new javax.swing.JMenuItem();
        mctAzul = new javax.swing.JMenuItem();
        mctRoxo = new javax.swing.JMenuItem();
        mctBranco = new javax.swing.JMenuItem();
        mcMarcaTexto = new javax.swing.JMenu();
        mcmVermelho = new javax.swing.JMenuItem();
        mcmLaranja = new javax.swing.JMenuItem();
        mcmAmarelo = new javax.swing.JMenuItem();
        mcmVerde = new javax.swing.JMenuItem();
        mcmAzul = new javax.swing.JMenuItem();
        mcmRoxo = new javax.swing.JMenuItem();
        mcmPreto = new javax.swing.JMenuItem();
        mcNormal = new javax.swing.JMenuItem();
        mnAjustes = new javax.swing.JMenu();
        btCentralizar = new javax.swing.JMenuItem();
        btAlinharDireita = new javax.swing.JMenuItem();
        btAlinharEsquerda = new javax.swing.JMenuItem();
        mnSobre = new javax.swing.JMenu();
        msMaisSobre = new javax.swing.JMenuItem();

        popTipoTexto.setText("Texto");

        popNegrito.setText("Negrito");
        popNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popNegritoActionPerformed(evt);
            }
        });
        popTipoTexto.add(popNegrito);

        popItalico.setText("Italico");
        popItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popItalicoActionPerformed(evt);
            }
        });
        popTipoTexto.add(popItalico);

        popSublinhado.setText("Sublinhado");
        popSublinhado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popSublinhadoActionPerformed(evt);
            }
        });
        popTipoTexto.add(popSublinhado);

        popNormal.setText("Normal");
        popNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popNormalActionPerformed(evt);
            }
        });
        popTipoTexto.add(popNormal);

        popupMenu.add(popTipoTexto);

        popCores.setText("Cores");

        popCorTexto.setText("Cor Texto");

        pctVermelho.setBackground(new java.awt.Color(255, 0, 0));
        pctVermelho.setText(" ");
        pctVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pctVermelhoActionPerformed(evt);
            }
        });
        popCorTexto.add(pctVermelho);

        pctLaranja.setBackground(new java.awt.Color(255, 153, 0));
        pctLaranja.setText(" ");
        pctLaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pctLaranjaActionPerformed(evt);
            }
        });
        popCorTexto.add(pctLaranja);

        pctAmarelo.setBackground(new java.awt.Color(255, 255, 0));
        pctAmarelo.setText(" ");
        pctAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pctAmareloActionPerformed(evt);
            }
        });
        popCorTexto.add(pctAmarelo);

        pctVerde.setBackground(new java.awt.Color(51, 255, 0));
        pctVerde.setText(" ");
        pctVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pctVerdeActionPerformed(evt);
            }
        });
        popCorTexto.add(pctVerde);

        pctAzul.setBackground(new java.awt.Color(0, 0, 255));
        pctAzul.setText(" ");
        pctAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pctAzulActionPerformed(evt);
            }
        });
        popCorTexto.add(pctAzul);

        pctRoxo.setBackground(new java.awt.Color(204, 0, 204));
        pctRoxo.setText(" ");
        pctRoxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pctRoxoActionPerformed(evt);
            }
        });
        popCorTexto.add(pctRoxo);

        pctBranco.setBackground(new java.awt.Color(255, 255, 255));
        pctBranco.setText(" ");
        pctBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pctBrancoActionPerformed(evt);
            }
        });
        popCorTexto.add(pctBranco);

        popCores.add(popCorTexto);

        popCorMarcador.setText("Cor Marcador");
        popCorMarcador.setToolTipText("");

        pcmVermelho.setBackground(new java.awt.Color(255, 0, 0));
        pcmVermelho.setText(" ");
        pcmVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcmVermelhoActionPerformed(evt);
            }
        });
        popCorMarcador.add(pcmVermelho);

        pcmLaranja.setBackground(new java.awt.Color(255, 153, 0));
        pcmLaranja.setText(" ");
        pcmLaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcmLaranjaActionPerformed(evt);
            }
        });
        popCorMarcador.add(pcmLaranja);

        pcmAmarelo.setBackground(new java.awt.Color(255, 255, 0));
        pcmAmarelo.setText(" ");
        pcmAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcmAmareloActionPerformed(evt);
            }
        });
        popCorMarcador.add(pcmAmarelo);

        pcmVerde.setBackground(new java.awt.Color(51, 255, 0));
        pcmVerde.setText(" ");
        pcmVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcmVerdeActionPerformed(evt);
            }
        });
        popCorMarcador.add(pcmVerde);

        pcmAzul.setBackground(new java.awt.Color(0, 0, 255));
        pcmAzul.setText(" ");
        pcmAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcmAzulActionPerformed(evt);
            }
        });
        popCorMarcador.add(pcmAzul);

        pcmRoxo.setBackground(new java.awt.Color(204, 0, 204));
        pcmRoxo.setText(" ");
        pcmRoxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcmRoxoActionPerformed(evt);
            }
        });
        popCorMarcador.add(pcmRoxo);

        pcmPreto.setBackground(new java.awt.Color(0, 0, 0));
        pcmPreto.setText(" ");
        pcmPreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcmPretoActionPerformed(evt);
            }
        });
        popCorMarcador.add(pcmPreto);

        popCores.add(popCorMarcador);

        popupMenu.add(popCores);

        popFonte.setText("Fonte");
        popFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popFonteActionPerformed(evt);
            }
        });
        popupMenu.add(popFonte);

        fcAbrirArquivo.setAcceptAllFileFilterUsed(false);
        fcAbrirArquivo.setFileFilter(filtroPoo);

        fcSalvarComo.setAcceptAllFileFilterUsed(false);
        fcSalvarComo.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fcSalvarComo.setFileFilter(filtroPoo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeWord");

        tpEscritaReleased.setMaximumSize(new java.awt.Dimension(100, 60));
        tpEscritaReleased.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tpEscritaReleasedMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tpEscritaReleasedMouseReleased(evt);
            }
        });
        tpEscritaReleased.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpEscritaReleasedKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tpEscritaReleased);

        btCorDoTexto.setBackground(new java.awt.Color(0, 0, 0));
        btCorDoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCorDoTextoActionPerformed(evt);
            }
        });

        lbCorDoTexto.setText("Cor do texto:");

        btCorMarcaTexto.setBackground(new java.awt.Color(255, 255, 255));
        btCorMarcaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCorMarcaTextoActionPerformed(evt);
            }
        });

        lbMarcaTexto.setText("Marca Texto:");

        cbItalico.setText("Itálico");
        cbItalico.setEnabled(false);
        cbItalico.setMaximumSize(new java.awt.Dimension(64, 16));
        cbItalico.setMinimumSize(new java.awt.Dimension(64, 16));
        cbItalico.setPreferredSize(new java.awt.Dimension(64, 16));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cbNegrito.setText("Negrito");
        cbNegrito.setEnabled(false);
        cbNegrito.setMaximumSize(new java.awt.Dimension(64, 16));
        cbNegrito.setMinimumSize(new java.awt.Dimension(64, 16));
        cbNegrito.setPreferredSize(new java.awt.Dimension(64, 16));
        cbNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNegritoActionPerformed(evt);
            }
        });

        cbUnderLine.setText("Sublinhado");
        cbUnderLine.setEnabled(false);
        cbUnderLine.setMaximumSize(new java.awt.Dimension(64, 16));
        cbUnderLine.setMinimumSize(new java.awt.Dimension(64, 16));
        cbUnderLine.setPreferredSize(new java.awt.Dimension(64, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUnderLine, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbItalico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNegrito, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMarcaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCorMarcaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCorDoTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCorDoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeDoc)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbItalico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbNegrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbUnderLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btCorMarcaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                        .addComponent(btCorDoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMarcaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCorDoTexto))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCorDoTexto, btCorMarcaTexto, lbCorDoTexto, lbMarcaTexto});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbItalico, cbNegrito, cbUnderLine});

        mnArquivo.setText("Arquivo");

        maAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        maAbrir.setText("Abrir ");
        maAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maAbrirActionPerformed(evt);
            }
        });
        mnArquivo.add(maAbrir);

        maNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        maNovo.setText("Novo");
        maNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maNovoActionPerformed(evt);
            }
        });
        mnArquivo.add(maNovo);

        maSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        maSalvar.setText("Salvar");
        maSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSalvarActionPerformed(evt);
            }
        });
        mnArquivo.add(maSalvar);

        maSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        maSalvarComo.setText("Salvar como");
        maSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSalvarComoActionPerformed(evt);
            }
        });
        mnArquivo.add(maSalvarComo);

        mainMenu.add(mnArquivo);

        mnTexto.setText("Texto");

        mtTipoTexto.setText("Tipo Texto");

        mtItalico.setText("Itálico");
        mtItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtItalicoActionPerformed(evt);
            }
        });
        mtTipoTexto.add(mtItalico);

        mtNegrito.setText("Negrito");
        mtNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtNegritoActionPerformed(evt);
            }
        });
        mtTipoTexto.add(mtNegrito);

        mtSublinhado.setText("Sublinhado");
        mtSublinhado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtSublinhadoActionPerformed(evt);
            }
        });
        mtTipoTexto.add(mtSublinhado);

        mnTexto.add(mtTipoTexto);

        btFonte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btFonte.setText("Fonte");
        btFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFonteActionPerformed(evt);
            }
        });
        mnTexto.add(btFonte);

        mtNormal.setText("Normal");
        mtNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtNormalActionPerformed(evt);
            }
        });
        mnTexto.add(mtNormal);

        mainMenu.add(mnTexto);

        mnCores.setText("Cores");

        mcCorDoTexto.setText("Texto");

        mctVermelho.setBackground(new java.awt.Color(255, 0, 0));
        mctVermelho.setText(" ");
        mctVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mctVermelhoActionPerformed(evt);
            }
        });
        mcCorDoTexto.add(mctVermelho);

        mctLaranja.setBackground(new java.awt.Color(255, 153, 0));
        mctLaranja.setText(" ");
        mctLaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mctLaranjaActionPerformed(evt);
            }
        });
        mcCorDoTexto.add(mctLaranja);

        mctAmarelo.setBackground(new java.awt.Color(255, 255, 0));
        mctAmarelo.setText(" ");
        mctAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mctAmareloActionPerformed(evt);
            }
        });
        mcCorDoTexto.add(mctAmarelo);

        mctVerde.setBackground(new java.awt.Color(51, 255, 0));
        mctVerde.setText(" ");
        mctVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mctVerdeActionPerformed(evt);
            }
        });
        mcCorDoTexto.add(mctVerde);

        mctAzul.setBackground(new java.awt.Color(0, 0, 255));
        mctAzul.setText(" ");
        mctAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mctAzulActionPerformed(evt);
            }
        });
        mcCorDoTexto.add(mctAzul);

        mctRoxo.setBackground(new java.awt.Color(204, 0, 204));
        mctRoxo.setText(" ");
        mctRoxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mctRoxoActionPerformed(evt);
            }
        });
        mcCorDoTexto.add(mctRoxo);

        mctBranco.setBackground(new java.awt.Color(255, 255, 255));
        mctBranco.setText(" ");
        mctBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mctBrancoActionPerformed(evt);
            }
        });
        mcCorDoTexto.add(mctBranco);

        mnCores.add(mcCorDoTexto);

        mcMarcaTexto.setText("Marca Texto");

        mcmVermelho.setBackground(new java.awt.Color(255, 0, 0));
        mcmVermelho.setText(" ");
        mcmVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmVermelhoActionPerformed(evt);
            }
        });
        mcMarcaTexto.add(mcmVermelho);

        mcmLaranja.setBackground(new java.awt.Color(255, 153, 0));
        mcmLaranja.setText(" ");
        mcmLaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmLaranjaActionPerformed(evt);
            }
        });
        mcMarcaTexto.add(mcmLaranja);

        mcmAmarelo.setBackground(new java.awt.Color(255, 255, 0));
        mcmAmarelo.setText(" ");
        mcmAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmAmareloActionPerformed(evt);
            }
        });
        mcMarcaTexto.add(mcmAmarelo);

        mcmVerde.setBackground(new java.awt.Color(51, 255, 0));
        mcmVerde.setText(" ");
        mcmVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmVerdeActionPerformed(evt);
            }
        });
        mcMarcaTexto.add(mcmVerde);

        mcmAzul.setBackground(new java.awt.Color(0, 0, 255));
        mcmAzul.setText(" ");
        mcmAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmAzulActionPerformed(evt);
            }
        });
        mcMarcaTexto.add(mcmAzul);

        mcmRoxo.setBackground(new java.awt.Color(204, 0, 204));
        mcmRoxo.setText(" ");
        mcmRoxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmRoxoActionPerformed(evt);
            }
        });
        mcMarcaTexto.add(mcmRoxo);

        mcmPreto.setBackground(new java.awt.Color(0, 0, 0));
        mcmPreto.setText(" ");
        mcmPreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcmPretoActionPerformed(evt);
            }
        });
        mcMarcaTexto.add(mcmPreto);

        mnCores.add(mcMarcaTexto);

        mcNormal.setText("Normal");
        mcNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcNormalActionPerformed(evt);
            }
        });
        mnCores.add(mcNormal);

        mainMenu.add(mnCores);

        mnAjustes.setText("Ajustes");

        btCentralizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btCentralizar.setText("Centralizar ");
        btCentralizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCentralizarMouseClicked(evt);
            }
        });
        btCentralizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCentralizarActionPerformed(evt);
            }
        });
        mnAjustes.add(btCentralizar);

        btAlinharDireita.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btAlinharDireita.setText("Alinhar Direita");
        btAlinharDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlinharDireitaActionPerformed(evt);
            }
        });
        mnAjustes.add(btAlinharDireita);

        btAlinharEsquerda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btAlinharEsquerda.setText("Alinhar Esquerda");
        btAlinharEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlinharEsquerdaActionPerformed(evt);
            }
        });
        mnAjustes.add(btAlinharEsquerda);

        mainMenu.add(mnAjustes);

        mnSobre.setText("Sobre");

        msMaisSobre.setText("Mais sobre");
        msMaisSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msMaisSobreActionPerformed(evt);
            }
        });
        mnSobre.add(msMaisSobre);

        mainMenu.add(mnSobre);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mtItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtItalicoActionPerformed
        c.trataTipoTexto("Italico");
        cbItalico.setSelected(!c.checkI);
    }//GEN-LAST:event_mtItalicoActionPerformed

    private void mtNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtNegritoActionPerformed
        c.trataTipoTexto("Negrito");
        cbNegrito.setSelected(!c.checkN);
    }//GEN-LAST:event_mtNegritoActionPerformed

    private void mctRoxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mctRoxoActionPerformed
        c.trataCorTexto(Color.magenta);
    }//GEN-LAST:event_mctRoxoActionPerformed

    private void mcmRoxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmRoxoActionPerformed
        c.trataCorMarcador(Color.magenta);
    }//GEN-LAST:event_mcmRoxoActionPerformed

    private void btCorDoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCorDoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCorDoTextoActionPerformed

    private void btCorMarcaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCorMarcaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCorMarcaTextoActionPerformed

    private void mctVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mctVermelhoActionPerformed
        c.trataCorTexto(Color.red);
    }//GEN-LAST:event_mctVermelhoActionPerformed

    private void mctLaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mctLaranjaActionPerformed
        c.trataCorTexto(Color.orange);
    }//GEN-LAST:event_mctLaranjaActionPerformed

    private void mctAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mctAmareloActionPerformed
        c.trataCorTexto(Color.yellow);
    }//GEN-LAST:event_mctAmareloActionPerformed

    private void mctVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mctVerdeActionPerformed
        c.trataCorTexto(Color.green);
    }//GEN-LAST:event_mctVerdeActionPerformed

    private void mctAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mctAzulActionPerformed
        c.trataCorTexto(Color.blue);
    }//GEN-LAST:event_mctAzulActionPerformed

    private void mcNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcNormalActionPerformed
        c.trataCorTexto(Color.black);
        c.trataCorMarcador(Color.white);
    }//GEN-LAST:event_mcNormalActionPerformed

    private void mcmVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmVermelhoActionPerformed
        c.trataCorMarcador(Color.red);
    }//GEN-LAST:event_mcmVermelhoActionPerformed

    private void mcmLaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmLaranjaActionPerformed
        c.trataCorMarcador(Color.orange);
    }//GEN-LAST:event_mcmLaranjaActionPerformed

    private void mcmAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmAmareloActionPerformed
        c.trataCorMarcador(Color.yellow);
    }//GEN-LAST:event_mcmAmareloActionPerformed

    private void mcmVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmVerdeActionPerformed
        c.trataCorMarcador(Color.green);
    }//GEN-LAST:event_mcmVerdeActionPerformed

    private void mcmAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmAzulActionPerformed
        c.trataCorMarcador(Color.blue);
    }//GEN-LAST:event_mcmAzulActionPerformed

    private void mctBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mctBrancoActionPerformed
        c.trataCorTexto(Color.white);
    }//GEN-LAST:event_mctBrancoActionPerformed

    private void mcmPretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcmPretoActionPerformed
        c.trataCorMarcador(Color.black);
    }//GEN-LAST:event_mcmPretoActionPerformed

    private void msMaisSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msMaisSobreActionPerformed
        s.setVisible(true);
    }//GEN-LAST:event_msMaisSobreActionPerformed

    private void mtNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtNormalActionPerformed
        c.trataTipoTexto("Normal");
        cbItalico.setSelected(false);
        cbNegrito.setSelected(false);
        cbUnderLine.setSelected(false);
    }//GEN-LAST:event_mtNormalActionPerformed

    private void mtSublinhadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtSublinhadoActionPerformed
        c.trataTipoTexto("UnderLine");
        cbUnderLine.setSelected(!c.checkU);
    }//GEN-LAST:event_mtSublinhadoActionPerformed

    private void btFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFonteActionPerformed
        c.trataTipoTexto("Fonte");
    }//GEN-LAST:event_btFonteActionPerformed

    private void btCentralizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCentralizarMouseClicked

    }//GEN-LAST:event_btCentralizarMouseClicked

    private void btCentralizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCentralizarActionPerformed
        c.centralizar();
    }//GEN-LAST:event_btCentralizarActionPerformed

    private void btAlinharEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlinharEsquerdaActionPerformed
        c.alinharEsquerda();
    }//GEN-LAST:event_btAlinharEsquerdaActionPerformed

    private void maAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maAbrirActionPerformed
        try {
            c.abrirArquivo(0);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maAbrirActionPerformed

    private void maNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maNovoActionPerformed
        try {
            c.novoArquivo();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maNovoActionPerformed

    private void maSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSalvarActionPerformed
        try {
            c.salvarArquivo();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maSalvarActionPerformed

    private void maSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSalvarComoActionPerformed
        try {
            c.salvarArquivoComo();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maSalvarComoActionPerformed

    private void btAlinharDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlinharDireitaActionPerformed
        c.alinharDireita();
    }//GEN-LAST:event_btAlinharDireitaActionPerformed

    private void tpEscritaReleasedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpEscritaReleasedKeyReleased
        c.textKeyUpdate();
    }//GEN-LAST:event_tpEscritaReleasedKeyReleased

    private void cbNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNegritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNegritoActionPerformed

    private void tpEscritaReleasedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpEscritaReleasedMousePressed
        if (evt.isPopupTrigger()) {
            showPopUp(evt);
        }
        c.posicaoCursor = tpEscritaReleased.getCaretPosition();
        c.auxPosicaoCursor = c.posicaoCursor;
    }//GEN-LAST:event_tpEscritaReleasedMousePressed

    private void tpEscritaReleasedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpEscritaReleasedMouseReleased
        if (evt.isPopupTrigger()) {
            showPopUp(evt);
        }
    }//GEN-LAST:event_tpEscritaReleasedMouseReleased

    private void popNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popNegritoActionPerformed
        c.trataTipoTextoPopup("Negrito");
        cbNegrito.setSelected(c.checkU);
    }//GEN-LAST:event_popNegritoActionPerformed

    private void popItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popItalicoActionPerformed
        c.trataTipoTextoPopup("Italico");
        cbItalico.setSelected(c.checkU);
    }//GEN-LAST:event_popItalicoActionPerformed

    private void popNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popNormalActionPerformed
        c.trataTipoTextoPopup("Normal");
        cbItalico.setSelected(false);
        cbNegrito.setSelected(false);
        cbUnderLine.setSelected(false);
    }//GEN-LAST:event_popNormalActionPerformed

    private void pctVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pctVermelhoActionPerformed
        c.trataCorTextoPopup(Color.red);
    }//GEN-LAST:event_pctVermelhoActionPerformed

    private void pctLaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pctLaranjaActionPerformed
        c.trataCorTextoPopup(Color.orange);
    }//GEN-LAST:event_pctLaranjaActionPerformed

    private void pctAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pctAmareloActionPerformed
        c.trataCorTextoPopup(Color.yellow);
    }//GEN-LAST:event_pctAmareloActionPerformed

    private void pctVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pctVerdeActionPerformed
        c.trataCorTextoPopup(Color.green);
    }//GEN-LAST:event_pctVerdeActionPerformed

    private void pctAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pctAzulActionPerformed
        c.trataCorTextoPopup(Color.blue);
    }//GEN-LAST:event_pctAzulActionPerformed

    private void pctRoxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pctRoxoActionPerformed
        c.trataCorTextoPopup(Color.magenta);
    }//GEN-LAST:event_pctRoxoActionPerformed

    private void pctBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pctBrancoActionPerformed
        c.trataCorTextoPopup(Color.white);
    }//GEN-LAST:event_pctBrancoActionPerformed

    private void pcmVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcmVermelhoActionPerformed
        c.trataCorMarcadorPopup(Color.red);
    }//GEN-LAST:event_pcmVermelhoActionPerformed

    private void pcmLaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcmLaranjaActionPerformed
        c.trataCorMarcadorPopup(Color.orange);
    }//GEN-LAST:event_pcmLaranjaActionPerformed

    private void pcmAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcmAmareloActionPerformed
        c.trataCorMarcadorPopup(Color.yellow);
    }//GEN-LAST:event_pcmAmareloActionPerformed

    private void pcmVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcmVerdeActionPerformed
        c.trataCorMarcadorPopup(Color.green);
    }//GEN-LAST:event_pcmVerdeActionPerformed

    private void pcmAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcmAzulActionPerformed
        c.trataCorMarcadorPopup(Color.blue);
    }//GEN-LAST:event_pcmAzulActionPerformed

    private void pcmRoxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcmRoxoActionPerformed
        c.trataCorMarcadorPopup(Color.magenta);
    }//GEN-LAST:event_pcmRoxoActionPerformed

    private void pcmPretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcmPretoActionPerformed
        c.trataCorMarcadorPopup(Color.black);
    }//GEN-LAST:event_pcmPretoActionPerformed

    private void popSublinhadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popSublinhadoActionPerformed
        c.trataTipoTextoPopup("UnderLine");
        cbUnderLine.setSelected(c.checkU);
    }//GEN-LAST:event_popSublinhadoActionPerformed

    private void popFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popFonteActionPerformed
        c.trataTipoTextoPopup("Fonte");
    }//GEN-LAST:event_popFonteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAlinharDireita;
    private javax.swing.JMenuItem btAlinharEsquerda;
    private javax.swing.JMenuItem btCentralizar;
    private javax.swing.JButton btCorDoTexto;
    private javax.swing.JButton btCorMarcaTexto;
    private javax.swing.JMenuItem btFonte;
    private javax.swing.JCheckBox cbItalico;
    private javax.swing.JCheckBox cbNegrito;
    private javax.swing.JCheckBox cbUnderLine;
    private javax.swing.JFileChooser fcAbrirArquivo;
    private javax.swing.JFileChooser fcSalvarComo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCorDoTexto;
    private javax.swing.JLabel lbMarcaTexto;
    private javax.swing.JLabel lbNomeDoc;
    private javax.swing.JMenuItem maAbrir;
    private javax.swing.JMenuItem maNovo;
    private javax.swing.JMenuItem maSalvar;
    private javax.swing.JMenuItem maSalvarComo;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu mcCorDoTexto;
    private javax.swing.JMenu mcMarcaTexto;
    private javax.swing.JMenuItem mcNormal;
    private javax.swing.JMenuItem mcmAmarelo;
    private javax.swing.JMenuItem mcmAzul;
    private javax.swing.JMenuItem mcmLaranja;
    private javax.swing.JMenuItem mcmPreto;
    private javax.swing.JMenuItem mcmRoxo;
    private javax.swing.JMenuItem mcmVerde;
    private javax.swing.JMenuItem mcmVermelho;
    private javax.swing.JMenuItem mctAmarelo;
    private javax.swing.JMenuItem mctAzul;
    private javax.swing.JMenuItem mctBranco;
    private javax.swing.JMenuItem mctLaranja;
    private javax.swing.JMenuItem mctRoxo;
    private javax.swing.JMenuItem mctVerde;
    private javax.swing.JMenuItem mctVermelho;
    private javax.swing.JMenu mnAjustes;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnCores;
    private javax.swing.JMenu mnSobre;
    private javax.swing.JMenu mnTexto;
    private javax.swing.JMenuItem msMaisSobre;
    private javax.swing.JMenuItem mtItalico;
    private javax.swing.JMenuItem mtNegrito;
    private javax.swing.JMenuItem mtNormal;
    private javax.swing.JMenuItem mtSublinhado;
    private javax.swing.JMenu mtTipoTexto;
    private javax.swing.JMenuItem pcmAmarelo;
    private javax.swing.JMenuItem pcmAzul;
    private javax.swing.JMenuItem pcmLaranja;
    private javax.swing.JMenuItem pcmPreto;
    private javax.swing.JMenuItem pcmRoxo;
    private javax.swing.JMenuItem pcmVerde;
    private javax.swing.JMenuItem pcmVermelho;
    private javax.swing.JMenuItem pctAmarelo;
    private javax.swing.JMenuItem pctAzul;
    private javax.swing.JMenuItem pctBranco;
    private javax.swing.JMenuItem pctLaranja;
    private javax.swing.JMenuItem pctRoxo;
    private javax.swing.JMenuItem pctVerde;
    private javax.swing.JMenuItem pctVermelho;
    private javax.swing.JMenu popCorMarcador;
    private javax.swing.JMenu popCorTexto;
    private javax.swing.JMenu popCores;
    private javax.swing.JMenuItem popFonte;
    private javax.swing.JMenuItem popItalico;
    private javax.swing.JMenuItem popNegrito;
    private javax.swing.JMenuItem popNormal;
    private javax.swing.JMenuItem popSublinhado;
    private javax.swing.JMenu popTipoTexto;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTextPane tpEscritaReleased;
    // End of variables declaration//GEN-END:variables
}
